id: IDD88E991
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T07:47:21+00:00'
last_modified: '2022-06-08T01:33:03.360175+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD159412
  title: རྡོ་དགོན་གསང་བདག་རྡོ་རྗེའི་རྩོམ་རིག་བརྩམས་ཆོས་ཕྱོགས་སྒྲིག།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    D37E:
      image_group_id: I2PD19610
      title: ''
      total_pages: 252
      order: 1
      base_file: D37E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
